project:
  type: book

execute:
  echo: false
  warning: false
  message: false
  error: true
  freeze: auto
  cache: false
  enabled: true
  
book:
  title: "Characteristics of the Mississippi Sound Estuary and Watershed"
  author: "Mississippi Sound Estuary Program"
  date: today
  date-format: long
  repo-url: https://github.com/CMEP-MS/msep_geospatialCharacterization
  repo-actions: [source]
  repo-link-target: "_blank"
  downloads: [pdf]
  cover-image: MSEP-logo.png
  cover-image-alt: "MSEP logo"
  navbar:
    logo: MSEP-logo2.png
  chapters:
    - index.qmd
    
    - part: geographic_setting.qmd
      chapters: 
        - HUCs.qmd
        - MDEQ_Basins.qmd
        - EPA_Ecoregions.qmd
    
    - part: climatology.qmd
      chapters: 
        - precipitation.qmd
        - temperature.qmd  
    
    - part: hydrology.qmd
      chapters: 
        - streams_waterbodies.qmd
        - freshwater_inflows.qmd
        - salinity.qmd
    
    - part: people_and_land_use.qmd
      chapters:
        - population.qmd
        - landuse_landcover.qmd
    
    - summary.qmd
    # - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    css: custom.css
  pdf:
    documentclass: scrreprt
    fig-pos: "H"
    tbl-pos: "H"


crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"

