# Data Processing  {#sec-dataProcessing}  

In general, links to original data sources are provided in each section below. Because data files are routinely updated, the files as downloaded and used in this document are also available online. These files are provided for reproducibility and transparency; for your own analyses, we encourage you to seek out data from the original linked sources.  

```{r}

```


## Geographic Setting  

### Watersheds {#sec-processingWatersheds}  

*Jump to @sec-Watersheds*

#### HUCs  

stuff

#### MDEQ Basins  

Shapefiles were provided by the Mississippi Department of Environmental Quality in August 2025. The zipped shapefiles are available in the [DEQ_basins](https://drive.google.com/drive/folders/1j-qbIAm_DVzoeyIU5EJgpUypAdNM0Lyc?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory. **However, we encourage you to contact MDEQ to get the most up-to-date files for your own analyses.**



### EPA Ecoregions {#sec-processingEPAEcoregions}  

*Jump to @sec-EPAEcoregions*

Level 3 and 4 Ecoregion shapefiles were downloaded from the [EPA's website](https://www.epa.gov/eco-research/level-iii-and-iv-ecoregions-state) on 16 June 2025 for the states of MS, AL, and LA.   

The original downloaded files along with their metadata files are available in the [EPA EcoRegions](https://drive.google.com/drive/folders/1Q8fZpHI-R40OW7dmQBE0e-VsQ0uSC7R1?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.  

Those files were read in, combined, and clipped to the Mississippi Sound Watershed boundaries (using the `outline_full` object from the [`{msepBoundaries}` package](https://github.com/CMEP-MS/msepBoundaries)) using the script `EPAEcoRegion_subsetting.R` ([on github](https://github.com/CMEP-MS/msep_geospatialCharacterization/blob/main/R_preprocessing/EPAEcoRegion_subsetting.R)) in the `R_preprocessing` folder. Three objects resulted: `level3_lamsal`, level 3 ecoregions for the 3 states combined; `level3_mssoundwatershed`, level 3 ecoregions trimmed to only the Mississippi Sound Watershed area; and `level4_mssoundwatershed`, level 4 ecoregions trimmed to only the Mississippi Sound Watershed area. The level 4 ecoregions for the entire three states were not retained because there were so many categories; it really only makes sense to look at these at the smaller level.  

The resulting objects were saved as layers of a geopackage,   `EPA_EcoRegion.gpkg` in the `data/processed` folder. These files are available in the [processed](https://drive.google.com/drive/folders/1vnTANkxh7lsAcTYFBr4sBuevKoYOGQG4?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.   

## Climatology   

### Precipitation {#sec-processingPrecipitation}  

*Jump to @sec-Precipitation*

Precipitation normals (over 15 and 30 years, and a 100-year baseline: 2006-2020, 1991-2020, and 1901-2000 respectively) were downloaded as "gridded normals" from the [National Centers for Environmental Information Climate Normals website](https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals) as netCDF (.nc) files. The downloaded files as used are available in the [Precipitation_NCEI](https://drive.google.com/drive/folders/13Qc-6VAia3fbVI9-mld_jnX_jQxoohDq?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.

These were subsetted to only monthly and annual value layers (removing layers with sd, min, max, and flags) and trimmed geographically to the states of MS, LA, and AL in the file `Precipitation_subsetting.R` ([on github](https://github.com/CMEP-MS/msep_geospatialCharacterization/blob/main/R_preprocessing/Precipitation_subsetting.R)) in the `R_preprocessing` folder.  

The resulting files were saved as netCDF files  `prcp_15yearNormals.nc`, `prcp_30yearNormals.nc`, and `prcp_100yearBaseline.nc` in the `data/processed` folder. These files are available in the [processed](https://drive.google.com/drive/folders/1vnTANkxh7lsAcTYFBr4sBuevKoYOGQG4?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.  


### Temperature {#sec-processingTemperature}  

*Jump to @sec-Temperature*

Average Temperature normals (over 15 and 30 years, and a 100-year baseline: 2006-2020, 1991-2020, and 1901-2000 respectively) were downloaded as "gridded normals" from the [National Centers for Environmental Information Climate Normals website](https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals) as netCDF (.nc) files. The downloaded files as used are available in the [Temperature_NCEI](https://drive.google.com/drive/folders/1C5PaE-9UhNleWuXcePL-33qVD_0p1Z8-?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.

These were subsetted to only monthly and annual value layers (removing layers with sd, min, max, and flags) and trimmed geographically to the states of MS, LA, and AL in the file `Temperature_subsetting.R` ([on github](https://github.com/CMEP-MS/msep_geospatialCharacterization/blob/main/R_preprocessing/Temperature_subsetting.R)) in the `R_preprocessing` folder.  

The resulting files were saved as netCDF files  `tempAvg_15yearNormals.nc`, `tempAvg_30yearNormals.nc`, and `tempAvg_100yearBaseline.nc` in the `data/processed` folder. These files are available in the [processed](https://drive.google.com/drive/folders/1vnTANkxh7lsAcTYFBr4sBuevKoYOGQG4?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.  


## Hydrology  

### Streams and Waterbodies {#sec-processingStreamsWaterbodies} 

*Jump to @sec-streamsWaterbodies*  


#### Stream Lengths and Waterbody Areas  

Stream Lengths and Waterbody Areas were calculated from the [EPA's NHDPlus](https://www.epa.gov/waterdata/nhdplus-national-hydrography-dataset-plus) dataset. Files for the [South Atlantic (03f)](https://www.epa.gov/waterdata/nhdplus-south-atlantic-west-data-vector-processing-unit-03w) and [Lower Mississippi River (03g)](https://www.epa.gov/waterdata/nhdplus-lower-mississippi-data-vector-processing-unit-08) regions were downloaded on 12 June 2025. The original downloaded files are available in the [EPA NHDPlus](https://drive.google.com/drive/folders/1QIMCH0Ae41V2k9ndVEZl-WMy8zcbbF1w?usp=sharing) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.  

Those files were read in, combined, and clipped to only the Mississippi Sound Watershed boundaries (using the `outline_full` object from the [`{msepBoundaries}` package](https://github.com/CMEP-MS/msepBoundaries)) using the script `EPANHD_subsetting.R` ([on github](https://github.com/CMEP-MS/msep_geospatialCharacterization/blob/main/R_preprocessing/EPANHD_subsetting.R)) in the `R_preprocessing` folder. The resulting files were saved as geopackages  `EPA_NHDplus_flowline_MSEP.gpkg` and `EPA_NHDplus_waterbody_MSEP.gpkg` in the `data/processed` folder. These files are available in the [processed](https://drive.google.com/drive/folders/1vnTANkxh7lsAcTYFBr4sBuevKoYOGQG4?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.  

#### Designated Uses  

Shapefiles of designated uses, already limited to the portion of the Mississippi Sound Watershed that lies within the state of MS, were provided by the Mississippi Department of Environmental Quality (MDEQ) in April 2025. These files provide the designated uses for each waterbody from the 2015 Water Quality Standards dataset. The Mississippi Sound Watershed is made up of MDEQ's Pearl River, Pascagoula River, and Coastal Streams basins. Per MDEQ, "all waters in those 3 basins not specifically listed in the data provided are classified as Fish and Wildlife." See [their website](https://www.mdeq.ms.gov/water/surface-water/watershed-management/water-quality-standards/basins-and-streams/) for more information.  

The zipped shapefiles are available in the [DEQ_designated_uses](https://drive.google.com/drive/folders/1JejePFJIRB0002POIhglPhP3YxWHvfqF?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory. **However, we encourage you to contact MDEQ to get the most up-to-date files for your own analyses.** 

#### Impairments  

Not done yet but see MDEQ's online [TMDL Tool](https://opcgis.deq.state.ms.us/tmdltool/).


### Freshwater Inflows {#sec-processingFreshwaterInflows} 

*Jump to @sec-freshwaterInflows*  

Stuff


### Salinity  {#sec-processingSalinity} 

*Jump to @sec-salinity*  

Stuff - Gulf Data Atlas especially  


## People and Land Use  

### Population  {#sec-processingPopulation}

*Jump to @sec-population*  


#### Dasymetric Population Estimates  

The [EPA EnviroAtlas's](https://www.epa.gov/enviroatlas/data-download) dasymetric population datasets "intelligently reallocate ... population from census blocks to 30 meter pixels based on land cover and slope". The national datasets for 2010 and 2020 were downloaded as raster files on 24 July 2025. Only the 2020 dataset has been used here.

The original downloaded file (zipped; ~3.6 GB) is available in the [Population](https://drive.google.com/drive/folders/1EBiRPhoXG1JNPFQDTasVWiJJI2LV6B-Y?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.  

The dataset was trimmed to Mississippi Sound Watershed boundaries (using the `outline_full` object from the [`{msepBoundaries}` package](https://github.com/CMEP-MS/msepBoundaries)) using the script `Population_2020_subsetting.R` ([on github](https://github.com/CMEP-MS/msep_geospatialCharacterization/blob/main/R_preprocessing/Population_2020_subsetting.R)) in the `R_preprocessing` folder. 

The resulting file, `Population_Dasymetric_2020.tif`, is available in the [processed](https://drive.google.com/drive/folders/1vnTANkxh7lsAcTYFBr4sBuevKoYOGQG4?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.  


### Land Use / Land Cover {#sec-processingLULC} 

*Jump to @sec-lulc*  

Land Use/Land Cover data was downloaded from the [USGS Annual National Land Cover Database](https://www.usgs.gov/centers/eros/science/annual-national-land-cover-database) in April 2025. Each pixel represents 30x30m.

The original downloaded file, `Annual_NLCD_LndCov_2023_CU_C1V0.tif` (~1.4 GB), covers the entire continental US and is available in the [NLCD](https://drive.google.com/drive/folders/17NVwSFlhkudjbZlCnzCbWmLcr52NuyHR?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.  

The dataset was trimmed to Mississippi Sound Watershed boundaries (using the `outline_full` object from the [`{msepBoundaries}` package](https://github.com/CMEP-MS/msepBoundaries)) using the script `NLCD_subsetting.R` ([on github](https://github.com/CMEP-MS/msep_geospatialCharacterization/blob/main/R_preprocessing/NLCD_subsetting.R)) in the `R_preprocessing` folder. Factor levels associated with the NLCD categories were also associated during this process and are part of the auxiliary file that loads with the dataset in R. 

The resulting files, `NLCD_MSEP.tif` and `NLCD_MSEP.tif.aux.xml` (the file with associated factor levels), are available in the [processed](https://drive.google.com/drive/folders/1vnTANkxh7lsAcTYFBr4sBuevKoYOGQG4?usp=drive_link) folder of the [msepCharacterization data files](https://drive.google.com/drive/folders/1Oyyrrjl0ygswBak5gbybVLYf5ENGUHD4?usp=sharing) directory.  




## About {.unnumbered}   

**The `.qmd` file** that generated this section was: **`r xfun::with_ext(knitr::current_input(), "qmd")`**. 

