# Watersheds {#sec-Watersheds}  

```{r}

```


## HUCs  

Nice explanation of HUCs on [this USGS page](https://nas.er.usgs.gov/hucs.aspx).  

The HUCs that make up the Mississippi Sound Watershed are 0317 (Pascagoula) and 0318 (Pearl).  

Show some mappy breakdowns.  


## MDEQ Basin Boundaries  

There are several waterways that don't actually end up in either the Pearl or Pascagoula Rivers. So the Mississippi Department of Environmental Quality uses a slightly different division.  

NEED TO CONFIRM, but I think: HUC12s are the same between MDEQ's classification and the USGS HUCs. They're just grouped differently, and the streams that empty into bays or straight into the Sound are the 'Coastal Streams Basin'. There is also a 'Coastal Offshore' grouping, that is comprised of the Sound itself, the islands, and the 3-mile zone beyond the islands.    


## About {.unnumbered}   

**The `.qmd` file** that generated this section was: **`r xfun::with_ext(knitr::current_input(), "qmd")`**. 

For information on data processing, see [Appendix @sec-processingWatersheds].